# Generated by Django 4.2.6 on 2023-10-06 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_image_name_image_data_image_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image_data',
            old_name='Image_name',
            new_name='Imagename',
        ),
        migrations.RenameField(
            model_name='image_data',
            old_name='Img_src',
            new_name='Imgsrc',
        ),
    ]
