# Generated by Django 4.2.6 on 2023-10-06 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_rename_imagename_image_data_imagname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image_data',
            old_name='Imagname',
            new_name='Imgname',
        ),
    ]
